### ISSUE TITLE
 require() of ES Module

### ISSUE THREAD

**Issue by christian-bromann** [saucelabs/node-saucelabs#205]
It seems like the recent update to the package, bumped the version of `got` to [`12.6.0`](https://github.com/saucelabs/node-saucelabs/pull/195/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R45) which is a ESM only package. This breaks the whole package because it runs in CJS (see #153).

Raised by https://github.com/webdriverio/webdriverio/issues/11077#issuecomment-1705243792

**Comment by diemol** [comment]
That was an oversight on my part. 

I will move `got` to `11.8.6` and make a new release.

**Comment by diemol** [comment]
7.3.1 is out.

**Comment by redbugz** [comment]
Seems we need a 7.3.2 for query-string now:
https://github.com/saucelabs/node-saucelabs/commit/a7814104cc324035901b9ade7d89c34182783175#commitcomment-127284025

**Comment by itssumitrai** [comment]
Same, seeing ES module issue with `query-string`

**Comment by diemol** [comment]
See https://github.com/saucelabs/node-saucelabs/issues/207

I will have time again to check this next week.

**Comment by snyamathi** [comment]
@diemol Has this change been release, or do you have time to create a release? I still see query-string v8.1.0 in the latest version

```
$ curl -s https://registry.npmjs.org/saucelabs/latest | jq '.dependencies' -
{
  "@xhmikosr/downloader": "^13.0.1",
  "change-case": "^4.1.2",
  "form-data": "^4.0.0",
  "got": "^11.8.6",
  "hash.js": "^1.1.7",
  "query-string": "^8.1.0",
  "tunnel": "^0.0.6",
  "yargs": "^17.2.1"
}
```

**Comment by diemol** [comment]
Work still needs to be done to fix this.

**Comment by lotuswood** [comment]
@diemol 
Based upon what I see in the 7.3.1 tag, I wonder if you can update your saucelabs/build/index.js to have
`const queryString = await import('./query-string'); `
instead of the current
`import queryString from 'query-string;'`

to fix this `required()` exception, given that cjs modules generally need to invoke esm modules using the dynamic import syntax as per suggested by the original error message?  

It may not be a good long term solution to downgrade your dependency of `query-string` to its older cjs module, if https://github.com/saucelabs/node-saucelabs/issues/207 is what you intend to release as a fix to this prob.
